AgoraVai/Models/Movimentacao.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AgoraVai.Models
{
    public class Movimentacao
    {
        [Key]
        public int Id { get; set; }
        public string Cpf { get; set; }
        public int Telefone { get; set; }
        public string Placa { get; set; }
        public int Tipo { get; set; }
        public DateTime hora_entrada { get; set; }
        public int FuncionarioId { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public DateTime? Hora_saida { get; set; }
        public decimal Valor_pagar { get; set; }
        public int VagaId { get; set; }
        public virtual Vaga Vaga { get; set; }
    }


    //public enum Tipo
    //{
    //    Diaria,
    //    Mensal,
    //    Semanal
    //}


}

AgoraVai/Controllers/EntradasController.cs
using AgoraVai.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgoraVai.Controllers
{
    public class EntradasController : Controller
    {
        private Contexto db = new Contexto();
        public static int tipovaga = 0;
        // GET: Entradas
        public ActionResult Create()
        {
            ViewBag.HoraEnt = DateTime.Now;
            ViewBag.FuncionarioId = new SelectList(db.Funcionario, "Id", "Email");
            ViewBag.VagaId = new SelectList(db.Vaga.Where(x => x.Quantidade > 0), "Id", "Tipo");
            ViewBag.TipoId = new SelectList(db.TipoPreco, "Id", "Tipo");
            //ViewBag.Tipo = new SelectList(Tip, "Id", "Tipo");
            return View();
        }

        [HttpPost]
          [ValidateAntiForgeryToken]
        public ActionResult Create(Entrada usu)
        {
            int sl = 0;
            sl = Convert.ToInt32(Session["FunID"]);
            Movimentacao mov = new Movimentacao();
            mov.Cpf = usu.Cpf;
            mov.Funcionario = usu.Funcionario;
            mov.hora_entrada = DateTime.Now;
            mov.Placa = usu.Placa;
            mov.Telefone = usu.Telefone;
           // mov.Funcionario = usu.Funcionario;
            mov.FuncionarioId = sl ;
            mov.Vaga = usu.Vaga;
            mov.VagaId = usu.VagaId;
            mov.Valor_pagar = 0;
            mov.Tipo = usu.TipoId;
            tipovaga = mov.Tipo = usu.TipoId;
            db.Movimentacao.Add(mov);
            db.SaveChanges();
            return RedirectToAction("Index", "movimentacaos");
        }

        /*
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Cpf,Telefone,Placa,hora_entrada,FuncionarioId,VagaId")] Movimentacao movimentacao)
        {

            movimentacao.hora_entrada = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Movimentacao.Add(movimentacao);
                db.SaveChanges();
                return RedirectToAction("Index","movimentacaos");
            }

            ViewBag.FuncionarioId = new SelectList(db.Funcionario, "Id", "Nome", movimentacao.FuncionarioId);
            ViewBag.VagaId = new SelectList(db.Vaga, "Id", "Tipo", movimentacao.VagaId);
            return View(movimentacao);
        }
        */
    }
}

AgoraVai/Controllers/MovimentacaosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AgoraVai.Models;

namespace AgoraVai.Controllers
{
    public class MovimentacaosController : Controller
    {
        private Contexto db = new Contexto();

        // GET: Movimentacaos
        public ActionResult Index()
        {
            int sl = 0;
            sl = Convert.ToInt32(Session["FunID"]);
            //ViewBag.ArrecadacaoDia = db.Movimentacao.Where(x => x.Hora_saida == DateTime.Now).Sum(x => x.Valor_pagar == 0f ? 0 : x.Valor_pagar);



            // ViewBag.Ex = db.Movimentacao.Where(x => x.Hora_saida != null).Sum(x => x.Valor_pagar == null ? 0 : x.Valor_pagar);

            // var movimentacao = db.Movimentacao.Include(m => m.Funcionario).Include(m => m.Vaga);

            //db.Movimentacao.ToList()

            Funcionario fun = db.Funcionario.Find(sl);
            ViewBag.nomedousuario = fun.Pessoa.Nome;


            
            return View(db.Movimentacao.Where(x => x.Valor_pagar == 0 && x.Funcionario.EstacionamentoId == fun.EstacionamentoId).ToList());
        }

        // GET: Movimentacaos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movimentacao movimentacao = db.Movimentacao.Find(id);
            if (movimentacao == null)
            {
                return HttpNotFound();
            }
            return View(movimentacao);
        }

        // GET: Movimentacaos/Create
        public ActionResult Create()
        {
            ViewBag.FuncionarioId = new SelectList(db.Funcionario, "Id", "Email");
            ViewBag.VagaId = new SelectList(db.Vaga, "Id", "Tipo");
            return View();
        }

        // POST: Movimentacaos/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Cpf,Telefone,Placa,hora_entrada,FuncionarioId,Hora_saida,Valor_pagar,VagaId")] Movimentacao movimentacao)
        {
            if (ModelState.IsValid)
            {
                db.Movimentacao.Add(movimentacao);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FuncionarioId = new SelectList(db.Funcionario, "Id", "Nome", movimentacao.FuncionarioId);
            ViewBag.VagaId = new SelectList(db.Vaga, "Id", "Tipo", movimentacao.VagaId);
            return View(movimentacao);
        }

        // GET: Movimentacaos/Edit/5
        public ActionResult Edit(int? id)
        {
            Movimentacao mov = db.Movimentacao.Find(id);
            ViewBag.horaSaida = DateTime.Now;
            ViewBag.Vp = calcularpreco(mov.hora_entrada, DateTime.Now, mov.Vaga, mov.Tipo);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movimentacao movimentacao = db.Movimentacao.Find(id);
            if (movimentacao == null)
            {
                return HttpNotFound();
            }
            return View(movimentacao);
        }

        // POST: Movimentacaos/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, Cpf, Telefone, Placa, hora_entrada, FuncionarioId, Hora_saida, Valor_pagar, VagaId")] Movimentacao movimentacao, int? id)
        {
            Movimentacao mov = db.Movimentacao.Find(id);
            //movimentacao.VagaId = mov.VagaId;
            //var vag = db.Vaga.FirstOrDefault(p => p.Id == mov.VagaId);
            //movimentacao.Cpf = mov.Cpf;
            //movimentacao.Telefone = mov.Telefone;
            //movimentacao.Placa = mov.Placa;
            //movimentacao.hora_entrada = mov.hora_entrada;
            //movimentacao.FuncionarioId = mov.FuncionarioId;
            mov.Hora_saida = DateTime.Now;
            mov.Valor_pagar = calcularpreco(mov.hora_entrada, mov.Hora_saida.Value, mov.Vaga, mov.Tipo);

            if (ModelState.IsValid)
            {
                db.Entry(mov).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = mov.Id });

            }
            return View(movimentacao);
        }

        public decimal calcularpreco(DateTime ent, DateTime sai, Vaga vag, int tipo)
        {
            decimal total = 0;
            TimeSpan tmp = sai - ent;
            int conta = 0;
            int sl = 0;
            sl = Convert.ToInt32(Session["FunID"]);
            Funcionario fun = db.Funcionario.Where(f => f.Id == sl).FirstOrDefault();
            Estacionamento est = db.Estacionamento.Where(e => e.Id == fun.EstacionamentoId).FirstOrDefault();

            if (vag.QuantidadeHorasEspeciais > 0)
                conta = vag.QuantidadeHorasEspeciais * 60;

            int tempo = (tmp.Hours) * 60 + tmp.Minutes;
            if (tipo == 1)
            {
                if (tempo >= 60 + est.Customizacoes.MinutosDeTolerancia)
                {
                    for (int i = tempo; i >= 0; i -= 60 + est.Customizacoes.MinutosDeTolerancia)
                    {
                        if (tempo > conta)
                        {
                            total += vag.valorHorasEspeciais;
                        }
                        else
                        {
                            total += vag.valor;
                        }
                    }
                }
                else
                {
                    total += vag.valor;
                }
            }
            else
            {
                total += vag.ValorMensal;
            }
            return total;
        }

        // GET: Movimentacaos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movimentacao movimentacao = db.Movimentacao.Find(id);
            if (movimentacao == null)
            {
                return HttpNotFound();
            }
            return View(movimentacao);
        }

        // POST: Movimentacaos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movimentacao movimentacao = db.Movimentacao.Find(id);
            db.Movimentacao.Remove(movimentacao);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AgoraVai/Controllers/VagasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AgoraVai.Models;

namespace AgoraVai.Controllers
{
    public class VagasController : Controller
    {
        private Contexto db = new Contexto();

        // GET: Vagas
        public ActionResult Index()
        {
            return View(db.Vaga.ToList());
        }

        // GET: Vagas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vaga vaga = db.Vaga.Find(id);
            if (vaga == null)
            {
                return HttpNotFound();
            }
            return View(vaga);
        }

        // GET: Vagas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vagas/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Tipo,valor,QuantidadeHorasEspeciais,valorHorasEspeciais,Quantidade")] Vaga vaga, string vv)
        {
            vaga.valor = Convert.ToDecimal(vv.Replace(".",","));
            //vaga.valor = Convert.ToDecimal(vv);
            if (ModelState.IsValid)
            {
                int sl = 0;
                sl = Convert.ToInt32(Session["GenID"]);
                vaga.EstacionamentoId = sl;
                vaga.Estacionamento = db.Estacionamento.Where(x => x.Id == vaga.EstacionamentoId).ToList().LastOrDefault();
                db.Vaga.Add(vaga);
                db.SaveChanges();
                return RedirectToAction("Index","Gerentes");
            }

            return View(vaga);
        }

        // GET: Vagas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vaga vaga = db.Vaga.Find(id);
            if (vaga == null)
            {
                return HttpNotFound();
            }
            return View(vaga);
        }

        // POST: Vagas/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Tipo,valor,Quantidade")] Vaga vaga)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vaga).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vaga);
        }

        // GET: Vagas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vaga vaga = db.Vaga.Find(id);
            if (vaga == null)
            {
                return HttpNotFound();
            }
            return View(vaga);
        }

        // POST: Vagas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vaga vaga = db.Vaga.Find(id);
            db.Vaga.Remove(vaga);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AgoraVai/Views/Shared/_Cadastros.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navegation">
        <img src="~/img/Logo.png" alt="">
        <ul>
            <li>@Html.ActionLink("Login", "Login", "Home", new { area = "" }, new { @class = "white" })</li>
        </ul>
    </nav>

    <main style="min-height: 90vh;">

        @RenderBody()

    </main>

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>

AgoraVai/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @*<nav class="navegation">
            <img src="~/img/Logo.png" alt="">
            <ul>
                <li>@Html.ActionLink("Entrada", "Create", "Entradas", new { area = "" }, new { @class = "white" })</li>
                <li>@Html.ActionLink("Movimentação", "Index", "Movimentacaos", new { area = "" }, new { @class = "white" })</li>
                <li>@Html.ActionLink("Sair", "Index", "Home", new { area = "" }, new { @class = "white" })</li>
            </ul>
        </nav>*@


    <main style="min-height: 90vh;">

        @RenderBody()

    </main>

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>

AgoraVai/Views/Shared/_Movimentacao.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navegation">
        <a href="@Url.Action("Index", "Movimentacaos")">
            <img src="~/img/Logo.png" alt="">
        </a>
        <ul>
            <li>@Html.ActionLink("Sangria", "Create", "Sangrias", new { area = "" }, new { @class = "white" })</li>
            <li>@Html.ActionLink("Entrada", "Create", "Entradas", new { area = "" }, new { @class = "white" })</li>
            <li>@Html.ActionLink("Sair", "Sair", "Home", new { area = "" }, new { @class = "white" })</li>
        </ul>
    </nav>

    <main>

        @RenderBody()

    </main>

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>

AgoraVai/Views/Shared/_TelaADM.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navegation">
        <a href="@Url.Action("Index", "CadastroGerente")">
            <img src="~/img/Logo.png" alt="">
        </a>
        @*@Html.ActionLink("Neo Virtual Park", "Index", "Estacionamentoes", new { area = "" }, new { @class = "white" })*@
        <ul>
            <li>@Html.ActionLink("Cadastrar Estacionamento", "Create", "CadastroGerente", new { area = "" }, new { @class = "white" })</li>
            <li>@Html.ActionLink("Sair", "Sair", "Home", new { area = "" }, new { @class = "white" })</li>
        </ul>
    </nav>

    <main style="min-height: 90vh;">

        @RenderBody()

    </main>

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>

AgoraVai/Views/Shared/_TelaGerente.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navegation">
        <a href="@Url.Action("Index", "Gerentes")">
            <img src="~/img/Logo.png" alt="">
        </a>
        @*@Html.ActionLink("Neo Virtual Park", "Index", "Estacionamentoes", new { area = "" }, new { @class = "white" })*@
        <ul>
            <li>@Html.ActionLink("Novo Funcionário", "Create", "CadastrarFunc", new { area = "" }, new { @class = "white" })</li>
            <li>@Html.ActionLink("Nova Vaga", "Create", "Vagas", new { area = "" }, new { @class = "white" })</li>
            <li>@Html.ActionLink("Registros", "Registros", "Gerentes", new { area = "" }, new { @class = "white" })</li>
            <li>@Html.ActionLink("Sangrias", "SangriasLista", "Gerentes", new { area = "" }, new { @class = "white" })</li>
            <li>@Html.ActionLink("Sair", "Sair", "Home", new { area = "" }, new { @class = "white" })</li>
        </ul>
    </nav>

    <main style="min-height: 90vh;">

        @RenderBody()

    </main>

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>